export const JUZ_INDEX = [
    { number: 1, startSurah: 1, startAyah: 1, startSurahName: "الفاتحة" },
    { number: 2, startSurah: 2, startAyah: 142, startSurahName: "سُورَةُ البَقَرَةِ" },
    { number: 3, startSurah: 2, startAyah: 253, startSurahName: "سُورَةُ البَقَرَةِ" },
    { number: 4, startSurah: 3, startAyah: 93, startSurahName: "سُورَةُ آلِ عِمۡرَانَ" },
    { number: 5, startSurah: 4, startAyah: 24, startSurahName: "سُورَةُ النِّسَاءِ" },
    { number: 6, startSurah: 4, startAyah: 148, startSurahName: "سُورَةُ النِّسَاءِ" },
    { number: 7, startSurah: 5, startAyah: 82, startSurahName: "سُورَةُ المَائـِدَةِ" },
    { number: 8, startSurah: 6, startAyah: 111, startSurahName: "سُورَةُ الأَنۡعَامِ" },
    { number: 9, startSurah: 7, startAyah: 88, startSurahName: "سُورَةُ الأَعۡرَافِ" },
    { number: 10, startSurah: 8, startAyah: 41, startSurahName: "سُورَةُ الأَنفَالِ" },
    { number: 11, startSurah: 9, startAyah: 93, startSurahName: "سُورَةُ التَّوۡبَةِ" },
    { number: 12, startSurah: 11, startAyah: 6, startSurahName: "سُورَةُ هُودٍ" },
    { number: 13, startSurah: 12, startAyah: 53, startSurahName: "سُورَةُ يُوسُفَ" },
    { number: 14, startSurah: 15, startAyah: 1, startSurahName: "سُورَةُ الحِجۡرِ" },
    { number: 15, startSurah: 17, startAyah: 1, startSurahName: "سُورَةُ الإِسۡرَاءِ" },
    { number: 16, startSurah: 18, startAyah: 75, startSurahName: "سُورَةُ الكَهۡفِ" },
    { number: 17, startSurah: 21, startAyah: 1, startSurahName: "سُورَةُ الأَنبِيَاءِ" },
    { number: 18, startSurah: 23, startAyah: 1, startSurahName: "سُورَةُ المُؤۡمِنُونَ" },
    { number: 19, startSurah: 25, startAyah: 21, startSurahName: "سُورَةُ الفُرۡقَانِ" },
    { number: 20, startSurah: 27, startAyah: 56, startSurahName: "سُورَةُ النَّمۡلِ" },
    { number: 21, startSurah: 29, startAyah: 46, startSurahName: "سُورَةُ العَنكَبُوتِ" },
    { number: 22, startSurah: 33, startAyah: 31, startSurahName: "سُورَةُ الأَحۡزَابِ" },
    { number: 23, startSurah: 36, startAyah: 28, startSurahName: "سُورَةُ يسٓ" },
    { number: 24, startSurah: 39, startAyah: 32, startSurahName: "سُورَةُ الزُّمَرِ" },
    { number: 25, startSurah: 41, startAyah: 47, startSurahName: "سُورَةُ فُصِّلَتۡ" },
    { number: 26, startSurah: 46, startAyah: 1, startSurahName: "سُورَةُ الأَحۡقَافِ" },
    { number: 27, startSurah: 51, startAyah: 31, startSurahName: "سُورَةُ الذَّارِيَاتِ" },
    { number: 28, startSurah: 58, startAyah: 1, startSurahName: "سُورَةُ المُجَادلَةِ" },
    { number: 29, startSurah: 67, startAyah: 1, startSurahName: "سُورَةُ المُلۡكِ" },
    { number: 30, startSurah: 78, startAyah: 1, startSurahName: "سُورَةُ النَّبَإِ" }
];

export const HIZB_INDEX = [
    { number: 1, startSurah: 1, startAyah: 1, startSurahName: "الفاتحة" },
    { number: 2, startSurah: 2, startAyah: 75, startSurahName: "سُورَةُ البَقَرَةِ" },
    { number: 3, startSurah: 2, startAyah: 142, startSurahName: "سُورَةُ البَقَرَةِ" },
    { number: 4, startSurah: 2, startAyah: 203, startSurahName: "سُورَةُ البَقَرَةِ" },
    { number: 5, startSurah: 2, startAyah: 253, startSurahName: "سُورَةُ البَقَرَةِ" },
    { number: 6, startSurah: 3, startAyah: 15, startSurahName: "سُورَةُ آلِ عِمۡرَانَ" },
    { number: 7, startSurah: 3, startAyah: 93, startSurahName: "سُورَةُ آلِ عِمۡرَانَ" },
    { number: 8, startSurah: 3, startAyah: 171, startSurahName: "سُورَةُ آلِ عِمۡرَانَ" },
    { number: 9, startSurah: 4, startAyah: 24, startSurahName: "سُورَةُ النِّسَاءِ" },
    { number: 10, startSurah: 4, startAyah: 88, startSurahName: "سُورَةُ النِّسَاءِ" },
    { number: 11, startSurah: 4, startAyah: 148, startSurahName: "سُورَةُ النِّسَاءِ" },
    { number: 12, startSurah: 5, startAyah: 27, startSurahName: "سُورَةُ المَائـِدَةِ" },
    { number: 13, startSurah: 5, startAyah: 82, startSurahName: "سُورَةُ المَائـِدَةِ" },
    { number: 14, startSurah: 6, startAyah: 36, startSurahName: "سُورَةُ الأَنۡعَامِ" },
    { number: 15, startSurah: 6, startAyah: 111, startSurahName: "سُورَةُ الأَنۡعَامِ" },
    { number: 16, startSurah: 6, startAyah: 141, startSurahName: "سُورَةُ الأَنۡعَامِ" },
    { number: 17, startSurah: 7, startAyah: 88, startSurahName: "سُورَةُ الأَعۡرَافِ" },
    { number: 18, startSurah: 7, startAyah: 142, startSurahName: "سُورَةُ الأَعۡرَافِ" },
    { number: 19, startSurah: 8, startAyah: 1, startSurahName: "سُورَةُ الأَنفَالِ" },
    { number: 20, startSurah: 8, startAyah: 41, startSurahName: "سُورَةُ الأَنفَالِ" },
    { number: 21, startSurah: 9, startAyah: 34, startSurahName: "سُورَةُ التَّوۡبَةِ" },
    { number: 22, startSurah: 9, startAyah: 93, startSurahName: "سُورَةُ التَّوۡبَةِ" },
    { number: 23, startSurah: 10, startAyah: 26, startSurahName: "سُورَةُ يُونُسَ" },
    { number: 24, startSurah: 11, startAyah: 6, startSurahName: "سُورَةُ هُودٍ" },
    { number: 25, startSurah: 11, startAyah: 84, startSurahName: "سُورَةُ هُودٍ" },
    { number: 26, startSurah: 12, startAyah: 53, startSurahName: "سُورَةُ يُوسُفَ" },
    { number: 27, startSurah: 13, startAyah: 19, startSurahName: "سُورَةُ الرَّعۡدِ" },
    { number: 28, startSurah: 15, startAyah: 1, startSurahName: "سُورَةُ الحِجۡرِ" },
    { number: 29, startSurah: 16, startAyah: 51, startSurahName: "سُورَةُ النَّحۡلِ" },
    { number: 30, startSurah: 17, startAyah: 1, startSurahName: "سُورَةُ الإِسۡرَاءِ" },
    { number: 31, startSurah: 17, startAyah: 99, startSurahName: "سُورَةُ الإِسۡرَاءِ" },
    { number: 32, startSurah: 18, startAyah: 75, startSurahName: "سُورَةُ الكَهۡفِ" },
    { number: 33, startSurah: 19, startAyah: 52, startSurahName: "سُورَةُ مَرۡيَمَ" },
    { number: 34, startSurah: 21, startAyah: 1, startSurahName: "سُورَةُ الأَنبِيَاءِ" },
    { number: 35, startSurah: 22, startAyah: 1, startSurahName: "سُورَةُ الحَجِّ" },
    { number: 36, startSurah: 23, startAyah: 1, startSurahName: "سُورَةُ المُؤۡمِنُونَ" },
    { number: 37, startSurah: 24, startAyah: 21, startSurahName: "سُورَةُ النُّورِ" },
    { number: 38, startSurah: 25, startAyah: 21, startSurahName: "سُورَةُ الفُرۡقَانِ" },
    { number: 39, startSurah: 26, startAyah: 111, startSurahName: "سُورَةُ الشُّعَرَاءِ" },
    { number: 40, startSurah: 27, startAyah: 56, startSurahName: "سُورَةُ النَّمۡلِ" },
    { number: 41, startSurah: 28, startAyah: 51, startSurahName: "سُورَةُ القَصَصِ" },
    { number: 42, startSurah: 29, startAyah: 46, startSurahName: "سُورَةُ العَنكَبُوتِ" },
    { number: 43, startSurah: 30, startAyah: 51, startSurahName: "سُورَةُ الرُّومِ" },
    { number: 44, startSurah: 33, startAyah: 31, startSurahName: "سُورَةُ الأَحۡزَابِ" },
    { number: 45, startSurah: 34, startAyah: 24, startSurahName: "سُورَةُ سَبَإٍ" },
    { number: 46, startSurah: 36, startAyah: 28, startSurahName: "سُورَةُ يسٓ" },
    { number: 47, startSurah: 37, startAyah: 145, startSurahName: "سُورَةُ الصَّافَّاتِ" },
    { number: 48, startSurah: 39, startAyah: 32, startSurahName: "سُورَةُ الزُّمَرِ" },
    { number: 49, startSurah: 40, startAyah: 41, startSurahName: "سُورَةُ غَافِرٍ" },
    { number: 50, startSurah: 41, startAyah: 47, startSurahName: "سُورَةُ فُصِّلَتۡ" },
    { number: 51, startSurah: 43, startAyah: 24, startSurahName: "سُورَةُ الزُّخۡرُفِ" },
    { number: 52, startSurah: 46, startAyah: 1, startSurahName: "سُورَةُ الأَحۡقَافِ" },
    { number: 53, startSurah: 48, startAyah: 18, startSurahName: "سُورَةُ الفَتۡحِ" },
    { number: 54, startSurah: 51, startAyah: 31, startSurahName: "سُورَةُ الذَّارِيَاتِ" },
    { number: 55, startSurah: 54, startAyah: 9, startSurahName: "سُورَةُ القَمَرِ" },
    { number: 56, startSurah: 58, startAyah: 1, startSurahName: "سُورَةُ المُجَادلَةِ" },
    { number: 57, startSurah: 61, startAyah: 1, startSurahName: "سُورَةُ الصَّفِّ" },
    { number: 58, startSurah: 67, startAyah: 1, startSurahName: "سُورَةُ المُلۡكِ" },
    { number: 59, startSurah: 72, startAyah: 1, startSurahName: "سُورَةُ الجِنِّ" },
    { number: 60, startSurah: 78, startAyah: 1, startSurahName: "سُورَةُ النَّبَإِ" }
];
